### ISSUE TITLE
demo data missing

### ISSUE THREAD

**Issue by 5rycaa** [ratschlab/scim#5]
Hi,

I am trying to implement SCIM in order to use it on my own data. I tried to follow your demo notebook, however the path to the demo data doesn't exist. Could you please add that? 

I even try to reverse-engineer it with my own data, but then I am still missing information like what type of data is stored in data.obs[is_train]. Thanks for your help!

**Comment by stefangstark** [comment]
Hi thanks for pointing this out.

For now, you can download the data by running the scripts/download.sh bash script. The README will be updated and a proper makefile will be added. 

Stefan

**Comment by stefangstark** [comment]
oops -- I had confused this with another repo, but the demo notebook generates the data it uses. I was able to install the environment and run the notebook without errors. The data the project uses should be available at the link in the readme, but it looks like this was become projected, which should not have happened.

**Comment by stefangstark** [comment]
download link has been updated
