### ISSUE TITLE
 DatasetV1Adapter object

### ISSUE THREAD

**Issue by 5rycaa** [ratschlab/scim#6]
Hi again!

I am getting an incompatible shape issue while trying to run training with VAE chunk of code. Going few steps back to the tensor slicing, I realized that I might be getting a wrong type of dataset. Namely, I am getting DatasetV1Adapter object. Am I supposed to have this format?
 
According to the issue [here](https://stackoverflow.com/questions/56963935/why-i-am-getting-datasetv1adapter-return-type-instead-of-tensorslicedataset-for), with tensorflow version below 2 (as in your case), the tf.data.Dataset.from_tensor_slices produces DatasetV1Adapter object instead of TensorSliceDataset, so I am wondering if that should be changed?

Thanks for your help

**Comment by stefangstark** [comment]
hmm, I installed the environment from scratch and ran the notebook without errors. Can you share more details on how you set up your environment?

**Comment by 5rycaa** [comment]
Hi again,

in simple terms, I actually have quite a complex environment set as a bridge between Py and R. 

Now, I think I solved my problem (I might write back again), which was the fact that anndata formats changed between your version (anndata==0.6.22.post1) and the current version used (anndata==0.7.6). So finally I re-installed your environment (based on requirements.txt), but had to update anndata, and now it seems to be working.

**Comment by 5rycaa** [comment]
Hi, just to give you a feedback - I think you can close the issue as I managed to reproduce the demo entirely.
